spring.application.name=TactiCoreWebUI
server.port=9090

api.base-url=http://localhost:8080

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.level.tr.com.huseyinaydin=DEBUG

spring.profiles.active=dev
