server.port=8081
api.base-url=http://localhost:8080
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.application.name=TactiCoreWebUI
logging.level.tr.com.huseyinaydin=DEBUG
spring.profiles.active=dev
